CreateThread(function()
  RegisterKeyMapping('jobpanel', 'Abrir panel de trabajos', 'keyboard')
  RegisterCommand('jobpanel', function()
    TriggerEvent('qb-jobcreator:client:openUI')
  end, false)
end)